#:schema node_modules/wrangler/config-schema.json
name = "master-gold-website"
compatibility_date = "2026-08-04"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"

[vars]
# You can place your public client-side variables here if needed
VITE_APP_NAME = "Master Gold Iran"

