#:schema node_modules/wrangler/config-schema.json
name = "master-gold-website-v2"
compatibility_date = "2026-07-12"

[assets]
directory = "./dist"

[vars]
# You can place your public client-side variables here if needed
VITE_APP_NAME = "Master Gold Iran"
